In [1]:
import pandas as pd
import numpy as np

In [2]:
origin_data_filename: str = "OriginData.dat"
origin_data_df: pd.DataFrame = pd.read_csv(origin_data_filename, delim_whitespace=True, header=None)
origin_data_df

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,61107.560,0.03224,0.03242,0.34241,0.22976,0.16684,0.26039,0.18440,2.04148,-0.16819,...,1.13234,0.67511,0.30921,1.33937,0.77916,0.26102,-0.60606,0.37710,0.18855,0.17785
1,61107.562,0.05330,0.05330,0.36966,0.25304,0.08952,0.17325,0.25735,0.70719,-0.07801,...,1.28643,0.65967,0.29712,-0.07708,0.80273,0.17288,0.10774,-0.16498,0.11111,0.34564
2,61107.564,0.07400,0.07399,0.38266,0.22267,0.03967,0.19757,0.15502,-1.12222,-0.11246,...,1.47802,0.56911,0.30619,0.58960,0.72084,-0.30169,-0.08418,-0.65657,0.25589,0.42953
3,61107.566,0.09287,0.09304,0.37833,0.21255,0.08240,0.26545,0.11044,-1.60000,0.02128,...,1.47093,0.44870,0.27597,0.77022,0.59553,-0.77627,-0.15488,-0.32660,-0.07407,0.76846
4,61107.568,0.10990,0.10989,0.35851,0.20850,0.17497,0.23100,0.13982,-0.62715,0.56839,...,1.33610,0.18318,0.20647,-0.65686,0.48263,-1.10101,1.32215,0.07407,-0.70707,1.30976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675,61122.550,-0.18713,-0.18658,0.31703,0.18623,0.21058,0.17933,-0.02736,0.56231,-0.12361,...,0.15814,-0.03808,0.02619,6.42865,-0.01737,-0.45085,-0.22896,-1.35811,-0.18519,1.23906
7676,61122.552,-0.20068,-0.20013,0.35851,0.18320,0.15666,0.11044,0.12766,1.19899,-0.06788,...,0.78362,0.34682,0.14806,5.78338,-0.27543,-0.16610,0.72727,-1.11824,-0.84175,0.57718
7677,61122.554,-0.19244,-0.19189,0.33994,0.15992,0.09156,-0.00101,0.15907,-0.66464,0.22999,...,0.86877,0.46928,0.21554,4.39037,-0.55335,0.21017,1.09060,-0.36364,-0.64310,-0.69463
7678,61122.556,-0.17065,-0.16992,0.26316,0.16397,0.08850,-0.01824,0.10638,-1.65859,-0.02634,...,0.02838,0.33138,0.22964,2.46173,-0.79404,0.13898,-0.21212,0.56902,0.41751,-0.47651
7679,61122.558,-0.13696,-0.13623,0.15851,0.17611,0.07935,0.05674,0.09726,0.51064,-0.28369,...,-0.38744,0.16569,0.16921,1.89870,-0.94293,-0.12542,-1.21141,0.58923,0.75084,-0.00336

In [3]:
output_data_columns = [
    "hour", "min", "sec", "msec",
    "pressure altitude", "calibrated airspeed", "mach",
    "angle of attack", "roll angle", "sideslip angle",
    "left flaperon position", "right flaperon position",
    "left horizontal tail position", "right horizontal tail position",
    "left rudder position", "right rudder position",
]
n_sensors: int = 28
sensor_name_list: list = ["sensor %d" % (i+1) for i in range(n_sensors)]
output_data_columns += sensor_name_list
output_data_df: pd.DataFrame = pd.DataFrame(columns=output_data_columns)
output_data_df

Empty DataFrame
Columns: [hour, min, sec, msec, pressure altitude, calibrated airspeed, mach, angle of attack, roll angle, sideslip angle, left flaperon position, right flaperon position, left horizontal tail position, right horizontal tail position, left rudder position, right rudder position, sensor 1, sensor 2, sensor 3, sensor 4, sensor 5, sensor 6, sensor 7, sensor 8, sensor 9, sensor 10, sensor 11, sensor 12, sensor 13, sensor 14, sensor 15, sensor 16, sensor 17, sensor 18, sensor 19, sensor 20, sensor 21, sensor 22, sensor 23, sensor 24, sensor 25, sensor 26, sensor 27, sensor 28]
Index: []

[0 rows x 44 columns]

# time

In [4]:
time = origin_data_df[0]
# break float time with units as second to hour, minute, second and millisecond
# add them to the output_data_df
output_data_df['hour'] = time.apply(lambda x: int(x/3600))
output_data_df['min'] = time.apply(lambda x: int((x%3600)/60))
output_data_df['sec'] = time.apply(lambda x: int(x%60))
output_data_df['msec'] = time.apply(lambda x: int((x%1)*1000))
output_data_df

,hour,min,sec,msec,pressure altitude,calibrated airspeed,mach,angle of attack,roll angle,sideslip angle,...,sensor 19,sensor 20,sensor 21,sensor 22,sensor 23,sensor 24,sensor 25,sensor 26,sensor 27,sensor 28
0,16,58,27,559,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,58,27,561,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,58,27,563,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,58,27,565,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,58,27,567,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675,16,58,42,550,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7676,16,58,42,552,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7677,16,58,42,553,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7678,16,58,42,555,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7679,16,58,42,557,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# flight parameters

In [5]:
n_rows: int = origin_data_df.shape[0]
# given pressure altitude increasing from 0 to 10000 ft
output_data_df['pressure altitude'] = np.linspace(0, 10000, n_rows)
# given calibrated airspped fluctuating between 900-1100 km/h randomly
output_data_df['calibrated airspeed'] = np.random.randint(900, 1100, n_rows)
# give mach number fluctuating between 0.7-0.9 randomly
output_data_df['mach'] = np.random.uniform(0.7, 0.9, n_rows)
# given angle of attack fluctuating between -10 to 10 degrees randomly
output_data_df['angle of attack'] = np.random.randint(-10, 10, n_rows)
# given roll angle fluctuating between -10 to 10 degrees randomly
output_data_df['roll angle'] = np.random.randint(-10, 10, n_rows)
# given sideslip angle fluctuating between -10 to 10 degrees randomly
output_data_df['sideslip angle'] = np.random.randint(-10, 10, n_rows)
# given left flaperon position fluctuating between -10 to 10 degrees randomly
output_data_df['left flaperon position'] = np.random.randint(-10, 10, n_rows)
# given right flaperon position fluctuating between -10 to 10 degrees randomly
output_data_df['right flaperon position'] = np.random.randint(-10, 10, n_rows)
# given left horizontal tail position fluctuating between -10 to 10 degrees randomly
output_data_df['left horizontal tail position'] = np.random.randint(-10, 10, n_rows)
# given right horizontal tail position fluctuating between -10 to 10 degrees randomly
output_data_df['right horizontal tail position'] = np.random.randint(-10, 10, n_rows)
# given left rudder position fluctuating between -10 to 10 degrees randomly
output_data_df['left rudder position'] = np.random.randint(-10, 10, n_rows)
# given right rudder position fluctuating between -10 to 10 degrees randomly
output_data_df['right rudder position'] = np.random.randint(-10, 10, n_rows)

output_data_df

,hour,min,sec,msec,pressure altitude,calibrated airspeed,mach,angle of attack,roll angle,sideslip angle,...,sensor 19,sensor 20,sensor 21,sensor 22,sensor 23,sensor 24,sensor 25,sensor 26,sensor 27,sensor 28
0,16,58,27,559,0.000000,1017,0.848357,-8,7,-7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,58,27,561,1.302253,987,0.893518,-1,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16,58,27,563,2.604506,982,0.733762,-4,8,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,58,27,565,3.906759,1093,0.707956,-10,6,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,58,27,567,5.209012,1090,0.820936,2,2,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675,16,58,42,550,9994.790988,1045,0.848377,1,-10,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7676,16,58,42,552,9996.093241,1026,0.809743,-7,-6,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7677,16,58,42,553,9997.395494,954,0.708300,6,-5,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7678,16,58,42,555,9998.697747,1086,0.742224,-1,-5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7679,16,58,42,557,10000.000000,944,0.703110,-5,-9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# sensor data

In [6]:
# let origin_data_df last n_sensors columns be the data of sensors
output_data_df.iloc[:, -n_sensors:] = origin_data_df.iloc[:, -n_sensors:]

C:\Users\bcynuaa\AppData\Local\Temp\ipykernel_13596\1069961491.py:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  output_data_df.iloc[:, -n_sensors:] = origin_data_df.iloc[:, -n_sensors:]

In [7]:
output_data_df

,hour,min,sec,msec,pressure altitude,calibrated airspeed,mach,angle of attack,roll angle,sideslip angle,...,sensor 19,sensor 20,sensor 21,sensor 22,sensor 23,sensor 24,sensor 25,sensor 26,sensor 27,sensor 28
0,16,58,27,559,0.000000,1017,0.848357,-8,7,-7,...,1.13234,0.67511,0.30921,1.33937,0.77916,0.26102,-0.60606,0.37710,0.18855,0.17785
1,16,58,27,561,1.302253,987,0.893518,-1,0,6,...,1.28643,0.65967,0.29712,-0.07708,0.80273,0.17288,0.10774,-0.16498,0.11111,0.34564
2,16,58,27,563,2.604506,982,0.733762,-4,8,5,...,1.47802,0.56911,0.30619,0.58960,0.72084,-0.30169,-0.08418,-0.65657,0.25589,0.42953
3,16,58,27,565,3.906759,1093,0.707956,-10,6,4,...,1.47093,0.44870,0.27597,0.77022,0.59553,-0.77627,-0.15488,-0.32660,-0.07407,0.76846
4,16,58,27,567,5.209012,1090,0.820936,2,2,-3,...,1.33610,0.18318,0.20647,-0.65686,0.48263,-1.10101,1.32215,0.07407,-0.70707,1.30976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675,16,58,42,550,9994.790988,1045,0.848377,1,-10,7,...,0.15814,-0.03808,0.02619,6.42865,-0.01737,-0.45085,-0.22896,-1.35811,-0.18519,1.23906
7676,16,58,42,552,9996.093241,1026,0.809743,-7,-6,3,...,0.78362,0.34682,0.14806,5.78338,-0.27543,-0.16610,0.72727,-1.11824,-0.84175,0.57718
7677,16,58,42,553,9997.395494,954,0.708300,6,-5,1,...,0.86877,0.46928,0.21554,4.39037,-0.55335,0.21017,1.09060,-0.36364,-0.64310,-0.69463
7678,16,58,42,555,9998.697747,1086,0.742224,-1,-5,0,...,0.02838,0.33138,0.22964,2.46173,-0.79404,0.13898,-0.21212,0.56902,0.41751,-0.47651
7679,16,58,42,557,10000.000000,944,0.703110,-5,-9,0,...,-0.38744,0.16569,0.16921,1.89870,-0.94293,-0.12542,-1.21141,0.58923,0.75084,-0.00336

In [8]:
output_data_df.to_csv("TestData.dat", sep='\t', index=False, header=True)